#! /bin/sh
set -euo pipefail

echo "OpenUDS Actor will be registered on the $OPENUDS_HOST"

echo "Install required OpenUDS packages"

apt-get -y install openuds-actor
apt-get -y install xrdp

echo "Enable required OpenUDS services"

systemctl enable udsactor
systemctl enable xrdp xrdp-sesman

echo "Configure OpenUDS actor"

printf "$OPENUDS_ACTOR_PRE_CONNECT\n$OPENUDS_ACTOR_RUN_ONCE\n$OPENUDS_ACTOR_POST_CONFIG\n" | UDSActorRegister

echo "Adding a test user to the tsusers group"

gpasswd -a test tsusers

echo "Depersonalization"

echo "" > /etc/hostname
echo "" > /etc/machine-id
rm -fr /var/lib/dbus
rm -f /etc/openssh/blacklist
rm -f /etc/openssh/ssh_host*
sed -i '/HOSTNAME/d' /etc/sysconfig/network

echo "Clear journalctl logs"

journalctl --rotate
journalctl --vacuum-time=1s

# echo "Setup network"

apt-get -y install cloud-init-config-network-manager