#! /bin/sh
set -euo pipefail

echo "=> Minimalizing VM for clouds..."

apt-get remove -y -D \
	dosfstools \
	eject \
	fatresize \
	firmware-linux \
	firmware-ast_dp501 \
	firmware-aic94xx-seq \
	firmware-ql6312 \
	hdparm \
	jfsutils \
	lftp \
	libaio \
	libtcl \
	lm_sensors3 \
	lvm2 \
	make-initrd-devmapper \
	make-initrd-luks \
	make-initrd-lvm \
	make-initrd-mdadm \
	mdadm \
	mdadm-tool \
	memtest86+ \
	mtools \
	nfs-utils \
	ntfs-3g \
	p7zip \
	postfix \
	postfix-control \
	ppp-common \
	procmail \
	reiserfsprogs \
	rp-pppoe-base \
	schedutils \
	smartmontools \
	tcl \
	usbutils \
	xfsprogs \

echo "=> Minimalizing VM for clouds completed"
