#! /bin/sh
set -euo pipefail

echo "Setting up motd"

apt-get update
apt-get install -y alt-issue
if test "${TARGET}" == "alt-server"; then
	apt-get install -y alt-issue-server
fi

echo "Motd set up"
